POST http://localhost:5000/api/account/createtoken
Content-Type: application/json

{
  "userID": "admin",
  "passWord": "admin"
}

###

@token={Replace with real token}
@id=1

###
GET http://localhost:5000/api/article/get/{{id}}
Content-Type: application/json

###
PUT http://localhost:5000/api/article/publish/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}