ALTER TABLE ArticleType ADD SEOTitle NVARCHAR(100);
ALTER TABLE ArticleType ADD SEOKeyWord NVARCHAR(100);
ALTER TABLE ArticleType ADD SEODescription NVARCHAR(300);

ALTER TABLE ProductCategory ADD SEOTitle NVARCHAR(100);
ALTER TABLE ProductCategory ADD SEOKeyWord NVARCHAR(100);
ALTER TABLE ProductCategory ADD SEODescription NVARCHAR(300);