CREATE DATABASE [$(dataBase)]
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [$(dataBase)].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [$(dataBase)] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [$(dataBase)] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [$(dataBase)] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [$(dataBase)] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [$(dataBase)] SET ARITHABORT OFF 
GO
ALTER DATABASE [$(dataBase)] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [$(dataBase)] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [$(dataBase)] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [$(dataBase)] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [$(dataBase)] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [$(dataBase)] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [$(dataBase)] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [$(dataBase)] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [$(dataBase)] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [$(dataBase)] SET  DISABLE_BROKER 
GO
ALTER DATABASE [$(dataBase)] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [$(dataBase)] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [$(dataBase)] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [$(dataBase)] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [$(dataBase)] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [$(dataBase)] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [$(dataBase)] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [$(dataBase)] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [$(dataBase)] SET  MULTI_USER 
GO
ALTER DATABASE [$(dataBase)] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [$(dataBase)] SET DB_CHAINING OFF 
GO
ALTER DATABASE [$(dataBase)] SET  READ_WRITE
GO